type:
    birthday: Symforce\AdminBundle\Compiler\MetaType\Form\Birthday
    bool: Symforce\AdminBundle\Compiler\MetaType\Form\Bool
    checkbox: Symforce\AdminBundle\Compiler\MetaType\Form\Checkbox
    choice: Symforce\AdminBundle\Compiler\MetaType\Form\Choice
    color: Symforce\AdminBundle\Compiler\MetaType\Form\Color
    county: Symforce\AdminBundle\Compiler\MetaType\Form\Country 
    datetime: Symforce\AdminBundle\Compiler\MetaType\Form\Datetime
    date: Symforce\AdminBundle\Compiler\MetaType\Form\Date
    time: Symforce\AdminBundle\Compiler\MetaType\Form\Time
    email: Symforce\AdminBundle\Compiler\MetaType\Form\Email
    embed: Symforce\AdminBundle\Compiler\MetaType\Form\Embed
    entity: Symforce\AdminBundle\Compiler\MetaType\Form\Entity
    file: Symforce\AdminBundle\Compiler\MetaType\Form\File
    hidden: Symforce\AdminBundle\Compiler\MetaType\Form\Hidden
    html: Symforce\AdminBundle\Compiler\MetaType\Form\Html
    image: Symforce\AdminBundle\Compiler\MetaType\Form\Image
    integer: Symforce\AdminBundle\Compiler\MetaType\Form\Integer
    language: Symforce\AdminBundle\Compiler\MetaType\Form\Language
    locale: Symforce\AdminBundle\Compiler\MetaType\Form\Locale
    markdown: Symforce\AdminBundle\Compiler\MetaType\Form\Markdown
    money: Symforce\AdminBundle\Compiler\MetaType\Form\Money
    password: Symforce\AdminBundle\Compiler\MetaType\Form\Password
    percent: Symforce\AdminBundle\Compiler\MetaType\Form\Percent
    radio: Symforce\AdminBundle\Compiler\MetaType\Form\Radio
    search: Symforce\AdminBundle\Compiler\MetaType\Form\Search
    text: Symforce\AdminBundle\Compiler\MetaType\Form\Text
    textarea: Symforce\AdminBundle\Compiler\MetaType\Form\Textarea
    timezone: Symforce\AdminBundle\Compiler\MetaType\Form\Timezone
    url: Symforce\AdminBundle\Compiler\MetaType\Form\Url
    workflow: Symforce\AdminBundle\Compiler\MetaType\Form\Workflow
    owner: Symforce\AdminBundle\Compiler\MetaType\Form\Owner
    range: Symforce\AdminBundle\Compiler\MetaType\Form\Range
    combobox: Symforce\AdminBundle\Compiler\MetaType\Form\Combobox
    tree:  Symforce\AdminBundle\Compiler\MetaType\Form\Tree
    json:  Symforce\AdminBundle\Compiler\MetaType\Form\Json
    route:  Symforce\AdminBundle\Compiler\MetaType\Form\Route
    template:  Symforce\AdminBundle\Compiler\MetaType\Form\Template
    
ignored_route:
    SensioDistributionBundle: ~
    SymforceAdminBundle: [ 'Ie', 'Secured', 'FileManager', 'Locale', 'FormHelper', 'Dashboard', 'Captcha' ]
    
ignored_template:
    SensioDistributionBundle: ~
    MopaBootstrapBundle: ~ 
    SecurityBundle: ~ 
    WebProfilerBundle: ~
    KnpPaginatorBundle: ~
    TwigBundle: [ 'Exception' ]
    SwiftmailerBundle: [ 'Collector' ]
    DoctrineBundle: [ 'Collector' ]
    SymforceAdminBundle: [ 'Secured', 'Form', 'Admin', 'Dashboard', 'FileManager', 'FormHelper', 'Locale', 'Menu' ]