
services:
    sf_routing.route_provider:
        class: Symforce\AdminBundle\Routing\RouteProvider
        arguments: [ "@doctrine", %sf_routing.entity_class%, %sf_routing.default_controller%, %sf_routing.default_template% ]
        
    sf_routing.url_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
        arguments: ["@cmf_routing.matcher.dummy_collection", "@cmf_routing.matcher.dummy_context"]

    sf_routing.nested_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher
        arguments: ["@sf_routing.route_provider"]
        calls:
            - [setFinalMatcher, ["@sf_routing.url_matcher"]]
    
    sf_routing.dynamic_router:
        class: Symfony\Cmf\Component\Routing\DynamicRouter
        arguments:
            - "@router.request_context"
            - "@sf_routing.nested_matcher"
            - "@cmf_routing.generator"
        tags:
            - { name: router, priority: 300 }