
_sf_admin_locale:
    prefix: %sf.web_assets_dir%
    resource: "@SymforceAdminBundle/Controller/LocaleController.php"
    type:     annotation

_sf_admin_captcha:
    prefix: %sf.web_assets_dir%
    resource: "@SymforceAdminBundle/Controller/CaptchaController.php"
    type:     annotation

_sf_admin_file_manager:
    prefix: %sf.web_assets_dir%
    resource: "@SymforceAdminBundle/Controller/FileManagerController.php"
    type:     annotation

_sf_admin_ie:
    prefix: %sf.web_assets_dir%
    resource: "@SymforceAdminBundle/Controller/IeController.php"
    type:     annotation

_sf_admin_dashboard:
    prefix: %sf.web_admin_dir%
    resource: "@SymforceAdminBundle/Controller/DashboardController.php"
    type:     annotation

_sf_admin_form_helper:
    prefix: %sf.web_admin_dir%
    resource: "@SymforceAdminBundle/Controller/FormHelperController.php"
    type:     annotation

_sf_admin_form_secured:
    prefix: %sf.web_admin_dir%
    resource: "@SymforceAdminBundle/Controller/SecuredController.php"
    type:     annotation

_sf_admin:
    resource: "."
    type: "sf_route_resource"