parameters:
    sf.admin.menu_builder.class: Symforce\AdminBundle\Menu\Builder
    # knp_menu.renderer.twig.class: Symforce\AdminBundle\Menu\BootstrapRenderer
    knp_menu.renderer.twig.template: "SymforceAdminBundle:Menu:menu_bootstrap.html.twig"
    # sf.admin.cache.path: "%kernel.cache_dir%/AdminLoaderCache.php"
    # sf.admin.cache.expired: "%kernel.cache_dir%/AdminLoaderExpired.php"
    # knp_menu.renderer.list.options: { currentClass: "active" }
    
services:
    # loader
    sf.admin.compiler:
        class: Symforce\AdminBundle\Compiler\Loader\Compiler
    
    sf.page.service:
        class: SymforceAdminCache\WebPageService
        calls:
            - [ setContainer, ["@service_container"] ]
            
    sf.page.menu:
        class: Symforce\AdminBundle\Service\MenuService
        calls:
            - [ setContainer, ["@service_container"] ]
    
    sf_router:
        alias: sf.page.service
        
    sf.admin.generator:
        class: Symforce\AdminBundle\Compiler\Generator
        arguments: [ "@service_container", null , null, null, null, null ]
 
    sf.admin.loader:
        class: Symforce\AdminBundle\Compiler\Loader\AdminLoader
        arguments: [ "@service_container", null, null ]
    
    sf.admin.imagine:
        class: Symforce\AdminBundle\Service\Imagine
        arguments: [ "@service_container" ]
    
    sf.form.factory:
        class: Symforce\AdminBundle\Compiler\MetaFormFactory
        arguments: [ "@doctrine", "@annotation_reader", null ]
    
    sf.locale.listener:
        class: Symforce\AdminBundle\Compiler\LocaleListener
        arguments: [ "@form.factory", null , null ]
        tags:
            - { name:"kernel.event_subscriber" }
            
    sf.form.listener:
        class: Symforce\AdminBundle\Event\FormSubscriber
        calls:
            - [ setContainer, ["@service_container"] ]
        tags:
            - { name:"kernel.event_subscriber" }

    # doctrine
    sf.repos.file:
        class: Symforce\AdminBundle\Entity\FileRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ Symforce\AdminBundle\Entity\File ]
        calls:
            - [ setContainer, ["@service_container"] ]

    # Router
    sf.route.loader:
        class: Symforce\AdminBundle\Compiler\Loader\RouteCacheLoader
        arguments: [ "@sf.admin.loader", null ]

    sf.routing.loader:
        class: Symforce\AdminBundle\Compiler\Loader\RoutingLoader
        public: false
        calls:
            - [ setContainer, ["@service_container"] ]
        tags:
            - { name:"routing.loader" }
    # Menu 
    sf.admin.menu_builder:
        class: "%sf.admin.menu_builder.class%"
        arguments: [ "@knp_menu.factory" ]
        calls:
            - [ setContainer, ["@service_container"] ]
            
    sf.admin.menu.admin:
        class: "%sf.admin.menu_builder.class%"
        factory_service: sf.admin.menu_builder
        factory_method: createDashboardMenu
        scope: "request"
        arguments: [ "@request" ]
        tags:
            - { name:"knp_menu.menu", alias:"admin"}
   
    # twig 
    sf.admin.twig.extension:
        public: false
        class: Symforce\AdminBundle\Twig\Extension\AppAdminTwigExtension
        arguments: [ "@twig.loader" ]
        calls:
            - [ setContainer, ["@service_container"] ]
        tags:
            - { name:"twig.extension" }
    # trans
    sf.translation.loader.yaml:
        class: Symforce\AdminBundle\Translation\Loader\AppTransLoader
        calls:
            - [ setMetaLoader, ["@sf.admin.loader"] ] 
        tags:
            - { name:"translation.loader", alias:"yaml" }

    # doctrine
    sf.admin.dbal.listener:
        class: Symforce\AdminBundle\Doctrine\DBAL\Listener\AdminListener
        public: false 
        calls:
            - [ setContainer, ["@service_container"] ]
        tags:
            - { name: doctrine.event_subscriber }
      